### ISSUE TITLE
v0.5 Tracking

### ISSUE THREAD

**Issue by adam-kerrigan** [adam-kerrigan/bader-rs#89]
Tracking for Critical Point Bond Analysis:

- [ ] Grid based saddle point detection
- [ ] Laplacian calculation
- [ ] Bonds across boundaries
- [ ] Intuitive representation of bonds

Changes to Methodology: 
- [ ] Run with an auto vacuum level as default
- [ ] Convert all Bader volumes to atoms
- [ ] Update movement to be lll-unit-cell as first thought
